####################################################################
#
# This file is part of exfor-parser.
# Copyright (C) 2022 International Atomic Energy Agency (IAEA)
#
# Disclaimer: The code is still under developments and not ready
#             to use. It has been made public to share the progress
#             among collaborators.
# Contact:    nds.contact-point@iaea.org
#
####################################################################

import os
import pandas as pd
import time
import hashlib
import git

# need version check based on the hash then the only new files should be processed

from exforparser.config import EXFOR_MASTER_REPO_PATH, ENTRY_INDEX_PICKLE, BUF_SIZE
from .exceptions import *

repo = git.Repo(EXFOR_MASTER_REPO_PATH)


"""
Run dos2unix for all .x4 files beforehand as follows:
for f in /Users/okumuras/Documents/nucleardata/EXFOR/X4all/*/*.x4; do dos2unix "$f"; done
"""


def rundos2unix(EXFOR_ALL_PATH):
    """May not needed anymore because exfor_master repository has done this"""
    glob = os.path.join(EXFOR_ALL_PATH, "*.x4")
    os.system('for f in glob; do dos2unix "$f"; done')

    return


def sha256_file(file):
    ## not used
    sha256 = hashlib.sha256()
    try:
        with open(file, "rb") as file:
            while True:
                # reading data = BUF_SIZE from
                # the file and saving it in a
                # variable
                data = file.read(BUF_SIZE)

                if not data:
                    break
    except:
        x4FileOpenError(file)

    return sha256.hexdigest()


def sha1_file(file):
    # Generate SHA1 806bc4fccac3d8a0b2105acd2e0e3f02b5f23737
    h = hashlib.sha1()
    try:
        with open(file, "rb") as f:
            h.update(f)
    except:
        x4FileOpenError(file)

    return h.hexdigest()


def git_hash(file):
    """Return the SHA-1 for each file generated by Git"""
    return repo.git.hash_object(file)


def git_last_commit(file):
    """Return name of the last commit"""
    print(file, repo.git.log("-1", "--pretty=%s", file))
    return repo.git.log("-1", "--pretty=%s", file)


def list_entries_from_pickle():
    """read exfor entry index pickle"""
    try:
        df = pd.read_pickle(ENTRY_INDEX_PICKLE)
        return df

    except FileNotFoundError:
        raise NoPickelExistenceError("../" + ENTRY_INDEX_PICKLE)


def list_exfor_files():
    ## loop over all entries and compose the list of entries
    files = []
    entries = []
    EXFOR_ALL_PATH = os.path.join(EXFOR_MASTER_REPO_PATH, "exforall")
    # rundos2unix(EXFOR_ALL_PATH)

    if os.path.exists(EXFOR_ALL_PATH):
        dirs = [f for f in os.listdir(EXFOR_ALL_PATH) if not f.startswith(".")]
        for d in dirs:
            files += [
                f
                for f in os.listdir(os.path.join(EXFOR_ALL_PATH, d))
                if f.endswith(".x4")
            ]

    else:
        Nox4FilesExistenceError(EXFOR_ALL_PATH)

    for file in files:
        entnum = file.split(".", 1)[0]
        file = f"exforall/{entnum[0:3]}/{entnum}.x4"

        sha1 = git_hash(file)
        last_modifieddate = git_last_commit(file)

        entries.append([entnum, last_modifieddate, sha1])

    df = pd.DataFrame(entries, columns=["entry", "latest_trans", "sha1"])
    df.to_pickle(ENTRY_INDEX_PICKLE)

    return df

good_example_entries = [
    "M0450",
    "D6274",
    "D0193",
    "20905",
    "40016",
    "22100",
    "T0243",
    "12240",
    "41185",
    "41102",
    "30010",
    "23134",  ## REACTION   (26-FE-56(N,INL)26-FE-56,PAR,SIG,G), E is specified as gamma energy
    "41119",  ## REACTION   (40-ZR-90(N,INL)40-ZR-90,PAR,SIG) why error?
    "30767",  # elem/mass and mass are in the same subent
    #    "D0545",  # ELEM1      MASS1      ELEM2      MASS2
    "20010",
    "10377",
    "A0927",  ## REACTION   (82-PB-208(P,X)83-BI-205,IND,SIG)
    "20802",
    "41500",  ## REACTION   (93-NP-237(N,F),DL,NU), delayed neutron yields
    "13668",  ## REACTION   (92-U-235(N,F),DL/GRP,NU)
    "41291",
    "12856",
    "40064",
    "C2522",
    "30772",
    "14534",
    "40674",
    "33084",  # nu
    "D0635",
    "C2540",
    "14463",
    "21332",  ## EN-RSL, CN,SIG
    "31714",  ## EN-RSL
    "A0493",  # REACTION   ((1-H-1(2-HE-6,EL)1-H-1,,DT)=(2-HE-6(P,EL)2-HE-6,,DT))
    "D6024",  ## E-LVL      E-EXC
    "40762",  # REACTION   (13-AL-27(N,EL)13-AL-27,,DA) X axis is given in COS
    "G0509",
    "32662",  # N,F with MASS
    "32718",  # fpy
    "22060",  # fpy
    "E0306",  # E-LVL, (12-MG-26(D,P)12-MG-27,PAR,DA)
    "14545",
    "40396",
    "C0380",
    "O0529",
    "10963",  # asymmetirc reaction (((30-ZN-64(N,EL),,WID,,G)*((30-ZN-64(N,G),,WID)+(30-ZN-64(N,EL),,WID,,FCT)))/(30-ZN-64(N,TOT),,WID))
    "14605",  # Istitute two rows with free text
    # "G0509",  # facility has pointer
    "O0191",
    "22436",
    "D0047",  # ((92-U-CMP(A,N),,PY,,TT)=(6-C-CMP(A,N),,PY,,TT))
    "12898",  # pointer ratio normal, from Amanda, ((23-V-51(N,P)22-TI-51,,SIG)/(92-U-238(N,F),,SIG))
    "41640",
    "11945",
    "11404",
    "11201",
    "22356",
    "E1814",
    "D6054",
    "C0194",
    "14537",  # R-value  (((94-PU-239(N,F)ELEM/MASS,CUM,FY,,FST)/(94-PU-239(N,F)42-MO-99,CUM,FY,,FST))//((92-U-235(N,F)ELEM/MASS,CUM,FY,,MXW)/(92-U-235(N,F)42-MO-99,CUM,FY,,MXW)))
    "21756",
    "13379",
    "30722",
    "30283",  # pointer + flag in 003 3(1.)
    "C0396",  # P,X SIG with ELEM/MASS
    "22374",  # heavy
    "14197",
    "14529",
    "12591",
    "31431",
    "D4030",
    "21107",
    "13500",
    "23313",
    "20010",  # REFERENCE  ((R,KFK-1000,1968)=(R,EUR-3963E,1968)= + \n (R,EANDC(E)-111,1968))
    "21902",
    "30328",
    "22331",
    "20802",  # facility and institute have pointer
    "21604",
    "12591",
    "32214",  # 003 contain only SUPPL-INFO, no REACTION
    "12505",
    "32610",
    "21756",
    "30310",
    "12570",
    "32619",
    "14498",
    "30006",
    "30391",
    "31754",
    "12599",
    "D4170",
    "11905",
    "30310",
    "30391",
    "30310",
    "11905",
    "33118",
    "F1246",
    "13297",
    "32804",
    "13025",
    "D4170",
    "A0631",
    "13569",
    "A0466",
    "13545",
    "11404",
    "32800",
    "31833",
    "31754",
    "31679",
    "12599",
    "12589",
    "12598",
    "12576",
    "12560",
    "12531",
    "12593",
    "12554",
    "12544",
    "30441",
    "30125",
    "31816",  # ratio ((xxx)//(ccc))
    "30275",
    "10536",
    "O1728",  # large DATA table with ELEM/MASS, Many DECAY-DATA
]

fpy_examples = [
    "14463",  # Energy is given in EN-MIN     EN-MAX
    # "40112", # cannot be processed until the entry is fixed (EN is givin twice in COMMON and DATA)
    "14555",
    "31802",
    "13445",
    "13444",
    "21595",  # 21595002-1: no incident energy is given, FST in reaction code
    "13302",
    "13353",  # SF
    "13455",
    "13081",
    "14259",
    "32662",  # N,F with MASS
    "32718",  # fpy
    "30791",  # MASS       ELEMENT    ISOMER     DATA       DATA-MIN   DATA-MAX    ERR-T      DECAY-FLAG FLAG
    "22470",
    "20384",  # no EN but resonance energy  REACTION   (94-PU-239(N,F)2-HE-4,TER,FY,,RES/REL)  EN-RES     DATA       ERR-S      FLAG
    "41179",  # no EN but resonance energy 41179003  (94-PU-239(N,F)ELEM/MASS,IND,FY,,RES/AV)
    "13443",  # no EN but EN-NM (nominator) 2(92-U-235(N,F)ELEM/MASS,CUM,FY)  EN-NM      EN-RSL     MASS       ELEMENT    ISOMER     DATA      1    ERR-S     1DATA      2MONIT1     MONIT2
    "14087",  # only EN-MIN from the middle of DATA REACTION   (92-U-233(N,F)ELEM/MASS,CUM,FY,,REL)  EN         EN-MIN     MASS       DATA       DATA-ERR
    "22060",
    "23583",
    "23342",
    "33030",
    "41198",
    "22985",
    "30787",
    "21706",
    "20848",
    "21218",
    "21549",
    "13333",
    "23558",
    "10517",
    "23780",
    "10798",
    "22062",
    "10964",
    "22111",
    "13053",
    "10828",
    "14625",
    "13981",  #  REACTION   (104-RF-262(0,F)MASS,PRE,FY)
    "14479",  #  REACTION   (98-CF-252(0,F)MASS,PR/PAR,FY,G)
    "41723",  #  REACTION   (92-U-235(N,F)ELEM/MASS,PR/PAR,FY,G)
    "22273",  #  REACTION  1(94-PU-239(N,F)MASS,SEC,FY,,,DERIV)
    "22757",  #  REACTION   (98-CF-252(0,F)MASS,PAR/PRE,FY,G)
    "O1012",  #  REACTION   (82-PB-208(92-U-238,F)ELEM,CHG,FY)
    "E1813",  #  REACTION   (94-PU-239(D,P+F)MASS,PAR/CHN,FY)
    "13584",  #  MASS       ELEMENT    ISOMER     DATA       DATA-ERR   DATA-MAX
    "13261",  #  REACTION   (98-CF-252(0,F)MASS,CHN,FY) MASS       DATA       ERR-S      DATA-ERR
    "40966",  #  REACTION   (92-U-235(N,F)ELEM/MASS,PAR/IND,FY,G)
    "14201",  #  REACTION   (92-U-235(N,F)0-G-0,PR/PAR,FY,,MXW)
    "13283",  #  Two FLAGs REACTION   (98-CF-252(0,F)ELEM/MASS,CUM,FY)  ELEMENT    MASS       DATA       DATA-ERR   FLAG       FLAG
    "14361",  #  REACTION  1(92-U-235(N,F)0-G-0,NUM,FY,,AV/RAW)
    "10979",  #  REACTION   (96-CM-248(0,F)MASS,CHN,FY)
    "13063",  #
    "23268",  #  REACTION   (98-CF-252(0,F)MASS,PRE,FY,,MSC)   Fission fragment yield as a function of pre-neutron  mass and TKE ( counts) .
    "41724",  #  REACTION   (96-CM-244(0,F),TER,FY,LCP)
    "C2469",
    "13444",
    "14555",
    "20381",
]


if __name__ == "__main__":
    list_exfor_files()
