####################################################################
#
# This file is part of exfor-parser.
# Copyright (C) 2022 International Atomic Energy Agency (IAEA)
#
# Disclaimer: The code is still under developments and not ready
#             to use. It has been made public to share the progress
#             among collaborators.
# Contact:    nds.contact-point@iaea.org
#
####################################################################

import os
import subprocess
import threading
import pandas as pd
import time
import hashlib
import git
from datetime import datetime, timezone

# need version check based on the hash then the only new files should be processed

from exforparser.config import EXFOR_MASTER_REPO_PATH, ENTRY_INDEX_PICKLE, ENTRY_INDEX_HEAD, BUF_SIZE
from .exceptions import *

repo = git.Repo(EXFOR_MASTER_REPO_PATH)


def _parse_entry_line(line: str) -> tuple[str, datetime | None]:
    """Extract (trans_code, trans_date) from an EXFOR ENTRY line.
    Example: 'ENTRY  L0156  20260309  20260422  20260422  L058'
    trans_code = last token; trans_date = second-to-last token parsed as YYYYMMDD.
    """
    parts = line.split()
    if len(parts) < 2:
        return "", None
    trans_code = parts[-1]
    trans_date = None
    if len(parts) >= 5:
        try:
            trans_date = datetime.strptime(parts[-2], "%Y%m%d")
        except ValueError:
            pass
    return trans_code, trans_date


def _batch_read_entry_lines(blob_shas: list[str]) -> dict[str, tuple[str, datetime | None]]:
    """Read the first (ENTRY) line from each blob via a single git cat-file --batch process.
    Streams input/output concurrently to keep memory bounded; skips content after the first line.
    Returns {blob_sha: (trans_code, trans_date)}.
    """
    if not blob_shas:
        return {}

    proc = subprocess.Popen(
        ["git", "cat-file", "--batch"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        cwd=EXFOR_MASTER_REPO_PATH,
    )

    def _write():
        proc.stdin.write(b"".join((s + "\n").encode() for s in blob_shas))
        proc.stdin.close()

    threading.Thread(target=_write, daemon=True).start()

    results = {}
    out = proc.stdout

    for sha in blob_shas:
        header = out.readline().decode("ascii", errors="replace").strip()
        parts = header.split()
        if len(parts) < 3 or parts[1] != "blob":
            results[sha] = ("", None)
            continue
        size = int(parts[2])
        first_line_bytes = out.readline()
        bytes_consumed = len(first_line_bytes)
        first_line = first_line_bytes.rstrip(b"\n\r").decode("utf-8", errors="replace")
        # Discard remaining object content + trailing protocol newline
        remaining = max(0, size - bytes_consumed + 1)
        while remaining > 0:
            chunk = out.read(min(65536, remaining))
            if not chunk:
                break
            remaining -= len(chunk)
        results[sha] = _parse_entry_line(first_line)

    proc.wait()
    return results


"""
Run dos2unix for all .x4 files beforehand as follows:
for f in /Users/okumuras/Documents/nucleardata/EXFOR/X4all/*/*.x4; do dos2unix "$f"; done
"""


def rundos2unix(EXFOR_ALL_PATH):
    """May not needed anymore because exfor_master repository has done this"""
    glob = os.path.join(EXFOR_ALL_PATH, "*.x4")
    os.system('for f in glob; do dos2unix "$f"; done')

    return


def sha256_file(file):
    ## not used
    sha256 = hashlib.sha256()
    try:
        with open(file, "rb") as file:
            while True:
                # reading data = BUF_SIZE from
                # the file and saving it in a
                # variable
                data = file.read(BUF_SIZE)

                if not data:
                    break
    except:
        x4FileOpenError(file)

    return sha256.hexdigest()


def sha1_file(file):
    # Generate SHA1 806bc4fccac3d8a0b2105acd2e0e3f02b5f23737
    h = hashlib.sha1()
    try:
        with open(file, "rb") as f:
            h.update(f)
    except:
        x4FileOpenError(file)

    return h.hexdigest()


def git_hash(file):
    """Return the SHA-1 for each file generated by Git"""
    return repo.git.hash_object(file)


def git_last_commit(file):
    """Return name of the last commit"""
    print(file, repo.git.log("-1", "--pretty=%s", file))
    return repo.git.log("-1", "--pretty=%s", file)


def git_all_hashes_for_file(rel_path: str) -> list[tuple]:
    """Return [(blob_sha1, committed_at), ...] for every commit that touched
    *rel_path*, newest-first.  Uses %at (Unix timestamp) for reliable parsing.
    """
    log_out = repo.git.log(
        "--follow",
        "--pretty=format:%H|%at",
        "--",
        rel_path,
    )
    results = []
    for line in log_out.strip().splitlines():
        if not line:
            continue
        parts = line.split("|", 1)
        if len(parts) < 2:
            continue
        commit_sha, unix_ts = parts
        ls_out = repo.git.ls_tree(commit_sha.strip(), "--", rel_path)
        if not ls_out:
            continue
        blob_sha = ls_out.split()[2]
        committed_at = datetime.fromtimestamp(
            int(unix_ts), tz=timezone.utc
        ).replace(tzinfo=None)
        results.append((blob_sha, committed_at))
    return results


def list_all_git_history() -> list[dict]:
    """Walk every .x4 file in the EXFOR master repo and collect the full git history.

    Returns a list of dicts with keys:
        entry, sha1, latest_trans, recorded_at, committed_at, is_current

    latest_trans and recorded_at are extracted from the ENTRY line of each blob.
    is_current=True only for the most recent commit per entry.
    Suitable for passing directly to backfill_history_from_git().
    """
    EXFOR_ALL_PATH = os.path.join(EXFOR_MASTER_REPO_PATH, "exforall")
    files = []
    if os.path.exists(EXFOR_ALL_PATH):
        dirs = [f for f in os.listdir(EXFOR_ALL_PATH) if not f.startswith(".")]
        for d in dirs:
            files += [
                f
                for f in os.listdir(os.path.join(EXFOR_ALL_PATH, d))
                if f.endswith(".x4")
            ]
    else:
        Nox4FilesExistenceError(EXFOR_ALL_PATH)

    # Phase 1: collect git metadata for every commit of every file
    raw_records = []
    for i, file in enumerate(files):
        entnum = file.split(".", 1)[0]
        rel_path = f"exforall/{entnum[0:3]}/{entnum}.x4"
        hashes = git_all_hashes_for_file(rel_path)
        for idx, (sha1, committed_at) in enumerate(hashes):
            raw_records.append(
                {
                    "entry": entnum,
                    "sha1": sha1,
                    "committed_at": committed_at,
                    "is_current": idx == 0,
                }
            )
        if (i + 1) % 500 == 0:
            print(f"  git history: scanned {i + 1}/{len(files)} files …")

    # Phase 2: batch-read the ENTRY line from every unique blob
    unique_shas = list({r["sha1"] for r in raw_records})
    print(f"  Reading ENTRY lines from {len(unique_shas)} unique blobs …")
    blob_entry_data = _batch_read_entry_lines(unique_shas)

    # Phase 3: merge ENTRY-line data into records
    all_records = []
    for r in raw_records:
        trans_code, trans_date = blob_entry_data.get(r["sha1"], ("", None))
        all_records.append(
            {
                **r,
                "latest_trans": trans_code,
                "recorded_at": trans_date,
            }
        )

    return all_records


def list_entries_from_pickle():
    """read exfor entry index pickle"""
    try:
        df = pd.read_pickle(ENTRY_INDEX_PICKLE)
        return df

    except FileNotFoundError:
        raise NoPickelExistenceError("../" + ENTRY_INDEX_PICKLE)


def _full_scan() -> pd.DataFrame:
    """Build the entry index from scratch using a single ls-tree call + batch blob read."""
    ls_tree_out = repo.git.ls_tree("-r", "HEAD", "--", "exforall/")
    entries = []
    for line in ls_tree_out.splitlines():
        # format: <mode> SP <type> SP <sha> TAB <path>
        meta, _, path = line.partition("\t")
        if not path.endswith(".x4"):
            continue
        blob_sha = meta.split()[2]
        entnum = os.path.basename(path).split(".", 1)[0]
        entries.append({"entry": entnum, "sha1": blob_sha})

    blob_entry_data = _batch_read_entry_lines([e["sha1"] for e in entries])

    rows = []
    for e in entries:
        trans_code, _ = blob_entry_data.get(e["sha1"], ("", None))
        rows.append({"entry": e["entry"], "latest_trans": trans_code, "sha1": e["sha1"]})

    return pd.DataFrame(rows, columns=["entry", "latest_trans", "sha1"])


def list_exfor_files(force: bool = False) -> pd.DataFrame:
    """Return a DataFrame of all EXFOR entries with their blob SHA and trans code.

    On first call (or when force=True) performs a full scan.  On subsequent calls
    compares the stored HEAD commit to the current one and only processes files that
    were added, modified, or deleted since the last run.
    """
    current_head = repo.head.commit.hexsha

    # --- incremental update ---
    if (
        not force
        and os.path.exists(ENTRY_INDEX_PICKLE)
        and os.path.exists(ENTRY_INDEX_HEAD)
    ):
        with open(ENTRY_INDEX_HEAD) as fh:
            stored_head = fh.read().strip()

        if stored_head == current_head:
            return pd.read_pickle(ENTRY_INDEX_PICKLE)

        try:
            diff_out = repo.git.diff(
                "--name-status", stored_head, current_head, "--", "exforall/"
            )
        except git.exc.GitCommandError:
            # The cached HEAD may come from a different/recloned exfor_master.
            # In that case the incremental diff cannot be computed safely.
            force = True
        else:
            force = False

        if force:
            df = _full_scan()
            df.to_pickle(ENTRY_INDEX_PICKLE)
            with open(ENTRY_INDEX_HEAD, "w") as fh:
                fh.write(current_head)
            return df

        df = pd.read_pickle(ENTRY_INDEX_PICKLE)

        for line in diff_out.splitlines():
            if not line:
                continue
            parts = line.split("\t")
            status = parts[0][0]  # A / M / D / R
            # renames: R<score> TAB old TAB new  — treat new path as modified
            path = parts[-1]
            if not path.endswith(".x4"):
                continue
            entnum = os.path.basename(path).split(".", 1)[0]
            df = df[df["entry"] != entnum]
            if status != "D":
                blob_sha = repo.git.ls_tree("HEAD", "--", path).split()[2]
                trans_code, _ = _batch_read_entry_lines([blob_sha]).get(blob_sha, ("", None))
                new_row = pd.DataFrame(
                    [{"entry": entnum, "latest_trans": trans_code, "sha1": blob_sha}]
                )
                df = pd.concat([df, new_row], ignore_index=True)

        df.to_pickle(ENTRY_INDEX_PICKLE)
        with open(ENTRY_INDEX_HEAD, "w") as fh:
            fh.write(current_head)
        return df

    # --- full scan ---
    EXFOR_ALL_PATH = os.path.join(EXFOR_MASTER_REPO_PATH, "exforall")
    if not os.path.exists(EXFOR_ALL_PATH):
        Nox4FilesExistenceError(EXFOR_ALL_PATH)

    df = _full_scan()
    df.to_pickle(ENTRY_INDEX_PICKLE)
    with open(ENTRY_INDEX_HEAD, "w") as fh:
        fh.write(current_head)
    return df


good_example_entries = [
    "M0450",
    "D6274",
    "D0193",
    "20905",
    "40016",
    "22100",
    "T0243",
    "12240",
    "41185",
    "41102",
    "30010",
    "23134",  ## REACTION   (26-FE-56(N,INL)26-FE-56,PAR,SIG,G), E is specified as gamma energy
    "41119",  ## REACTION   (40-ZR-90(N,INL)40-ZR-90,PAR,SIG) why error?
    "30767",  # elem/mass and mass are in the same subent
    #    "D0545",  # ELEM1      MASS1      ELEM2      MASS2
    "20010",
    "10377",
    "A0927",  ## REACTION   (82-PB-208(P,X)83-BI-205,IND,SIG)
    "20802",
    "41500",  ## REACTION   (93-NP-237(N,F),DL,NU), delayed neutron yields
    "13668",  ## REACTION   (92-U-235(N,F),DL/GRP,NU)
    "41291",
    "12856",
    "40064",
    "C2522",
    "30772",
    "14534",
    "40674",
    "33084",  # nu
    "D0635",
    "C2540",
    "14463",
    "21332",  ## EN-RSL, CN,SIG
    "31714",  ## EN-RSL
    "A0493",  # REACTION   ((1-H-1(2-HE-6,EL)1-H-1,,DT)=(2-HE-6(P,EL)2-HE-6,,DT))
    "D6024",  ## E-LVL      E-EXC
    "40762",  # REACTION   (13-AL-27(N,EL)13-AL-27,,DA) X axis is given in COS
    "G0509",
    "32662",  # N,F with MASS
    "32718",  # fpy
    "22060",  # fpy
    "E0306",  # E-LVL, (12-MG-26(D,P)12-MG-27,PAR,DA)
    "14545",
    "40396",
    "C0380",
    "O0529",
    "10963",  # asymmetirc reaction (((30-ZN-64(N,EL),,WID,,G)*((30-ZN-64(N,G),,WID)+(30-ZN-64(N,EL),,WID,,FCT)))/(30-ZN-64(N,TOT),,WID))
    "14605",  # Istitute two rows with free text
    # "G0509",  # facility has pointer
    "O0191",
    "22436",
    "D0047",  # ((92-U-CMP(A,N),,PY,,TT)=(6-C-CMP(A,N),,PY,,TT))
    "12898",  # pointer ratio normal, from Amanda, ((23-V-51(N,P)22-TI-51,,SIG)/(92-U-238(N,F),,SIG))
    "41640",
    "11945",
    "11404",
    "11201",
    "22356",
    "E1814",
    "D6054",
    "C0194",
    "14537",  # R-value  (((94-PU-239(N,F)ELEM/MASS,CUM,FY,,FST)/(94-PU-239(N,F)42-MO-99,CUM,FY,,FST))//((92-U-235(N,F)ELEM/MASS,CUM,FY,,MXW)/(92-U-235(N,F)42-MO-99,CUM,FY,,MXW)))
    "21756",
    "13379",
    "30722",
    "30283",  # pointer + flag in 003 3(1.)
    "C0396",  # P,X SIG with ELEM/MASS
    "22374",  # heavy
    "14197",
    "14529",
    "12591",
    "31431",
    "D4030",
    "21107",
    "13500",
    "23313",
    "20010",  # REFERENCE  ((R,KFK-1000,1968)=(R,EUR-3963E,1968)= + \n (R,EANDC(E)-111,1968))
    "21902",
    "30328",
    "22331",
    "20802",  # facility and institute have pointer
    "21604",
    "12591",
    "32214",  # 003 contain only SUPPL-INFO, no REACTION
    "12505",
    "32610",
    "21756",
    "30310",
    "12570",
    "32619",
    "14498",
    "30006",
    "30391",
    "31754",
    "12599",
    "D4170",
    "11905",
    "30310",
    "30391",
    "30310",
    "11905",
    "33118",
    "F1246",
    "13297",
    "32804",
    "13025",
    "D4170",
    "A0631",
    "13569",
    "A0466",
    "13545",
    "11404",
    "32800",
    "31833",
    "31754",
    "31679",
    "12599",
    "12589",
    "12598",
    "12576",
    "12560",
    "12531",
    "12593",
    "12554",
    "12544",
    "30441",
    "30125",
    "31816",  # ratio ((xxx)//(ccc))
    "30275",
    "10536",
    "O1728",  # large DATA table with ELEM/MASS, Many DECAY-DATA
]

fpy_examples = [
    "14463",  # Energy is given in EN-MIN     EN-MAX
    # "40112", # cannot be processed until the entry is fixed (EN is givin twice in COMMON and DATA)
    "14555",
    "31802",
    "13445",
    "13444",
    "21595",  # 21595002-1: no incident energy is given, FST in reaction code
    "13302",
    "13353",  # SF
    "13455",
    "13081",
    "14259",
    "32662",  # N,F with MASS
    "32718",  # fpy
    "30791",  # MASS       ELEMENT    ISOMER     DATA       DATA-MIN   DATA-MAX    ERR-T      DECAY-FLAG FLAG
    "22470",
    "20384",  # no EN but resonance energy  REACTION   (94-PU-239(N,F)2-HE-4,TER,FY,,RES/REL)  EN-RES     DATA       ERR-S      FLAG
    "41179",  # no EN but resonance energy 41179003  (94-PU-239(N,F)ELEM/MASS,IND,FY,,RES/AV)
    "13443",  # no EN but EN-NM (nominator) 2(92-U-235(N,F)ELEM/MASS,CUM,FY)  EN-NM      EN-RSL     MASS       ELEMENT    ISOMER     DATA      1    ERR-S     1DATA      2MONIT1     MONIT2
    "14087",  # only EN-MIN from the middle of DATA REACTION   (92-U-233(N,F)ELEM/MASS,CUM,FY,,REL)  EN         EN-MIN     MASS       DATA       DATA-ERR
    "22060",
    "23583",
    "23342",
    "33030",
    "41198",
    "22985",
    "30787",
    "21706",
    "20848",
    "21218",
    "21549",
    "13333",
    "23558",
    "10517",
    "23780",
    "10798",
    "22062",
    "10964",
    "22111",
    "13053",
    "10828",
    "14625",
    "13981",  #  REACTION   (104-RF-262(0,F)MASS,PRE,FY)
    "14479",  #  REACTION   (98-CF-252(0,F)MASS,PR/PAR,FY,G)
    "41723",  #  REACTION   (92-U-235(N,F)ELEM/MASS,PR/PAR,FY,G)
    "22273",  #  REACTION  1(94-PU-239(N,F)MASS,SEC,FY,,,DERIV)
    "22757",  #  REACTION   (98-CF-252(0,F)MASS,PAR/PRE,FY,G)
    "O1012",  #  REACTION   (82-PB-208(92-U-238,F)ELEM,CHG,FY)
    "E1813",  #  REACTION   (94-PU-239(D,P+F)MASS,PAR/CHN,FY)
    "13584",  #  MASS       ELEMENT    ISOMER     DATA       DATA-ERR   DATA-MAX
    "13261",  #  REACTION   (98-CF-252(0,F)MASS,CHN,FY) MASS       DATA       ERR-S      DATA-ERR
    "40966",  #  REACTION   (92-U-235(N,F)ELEM/MASS,PAR/IND,FY,G)
    "14201",  #  REACTION   (92-U-235(N,F)0-G-0,PR/PAR,FY,,MXW)
    "13283",  #  Two FLAGs REACTION   (98-CF-252(0,F)ELEM/MASS,CUM,FY)  ELEMENT    MASS       DATA       DATA-ERR   FLAG       FLAG
    "14361",  #  REACTION  1(92-U-235(N,F)0-G-0,NUM,FY,,AV/RAW)
    "10979",  #  REACTION   (96-CM-248(0,F)MASS,CHN,FY)
    "13063",  #
    "23268",  #  REACTION   (98-CF-252(0,F)MASS,PRE,FY,,MSC)   Fission fragment yield as a function of pre-neutron  mass and TKE ( counts) .
    "41724",  #  REACTION   (96-CM-244(0,F),TER,FY,LCP)
    "C2469",
    "13444",
    "14555",
    "20381",
]


if __name__ == "__main__":
    list_exfor_files()
