# name: Auto Update

# on:
#   schedule:
#     - cron: '0 13 * * 1,3,5' # runs at 13:00 UTC every Mon., Wed., Fri.



# This is a basic workflow that is manually triggered
name: Manual Update

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Run'
        default: 'Now'
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.runpy.outputs.test }}

    steps:

      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # fetch-depth: 0


      - uses: fregante/setup-git-user@v1


      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
  


      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script 
        id: runpy
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          cd ${GITHUB_WORKSPACE}
          git clone https://github.com/IAEA-NDS/exfor_dictionary.git
          git clone https://github.com/IAEA-NDS/exfor_master.git
          git clone https://github.com/IAEA-NDS/exfor_json.git
          python exparser.py


      - name: run entry update list file script and commit file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add json/*
          git commit -m "update json files"
          git push origin main
